"""empty message

Revision ID: 74e56944af24
Revises: 03316db0a82b
Create Date: 2023-06-06 18:16:06.473895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e56944af24'
down_revision = '03316db0a82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('is_followed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_followed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
